apiVersion: skaffold/v4beta5
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl: {}
build:
  local:
    push: false
  # googleCloudBuild:
  #   projectId: eco-droplet-388007
  artifacts:
    # - image: us.gcr.io/eco-droplet-388007/auth
    - image: deokwons9004dev/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: deokwons9004dev/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: deokwons9004dev/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: deokwons9004dev/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: deokwons9004dev/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: deokwons9004dev/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .